/*
 * File: DataAccessClientViewport.js
 * Date: Wed Dec 01 2010 00:33:40 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

DataAccessClientViewport = Ext.extend(DataAccessClientViewportUi, {
    initComponent: function() {
        DataAccessClientViewport.superclass.initComponent.call(this);
    }
});
