/*
 * File: xds_index.js
 * Date: Sun Dec 05 2010 17:01:14 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new DataAccessClientViewport({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
