/*
 * File: PartStore.js
 * Date: Thu Dec 02 2010 20:38:56 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

PartStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        PartStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'partStore',
            root: 'abstractparts',
            url: '../data/abstractparts.json',
            autoLoad: true,
            fields: [
                {
                    name: 'id',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'description',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'sequence',
                    type: 'string'
                },
                {
                    name: 'biofunction',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'type',
                    allowBlank: false,
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
new PartStore();